# Generated by Django 5.2.5 on 2025-08-14 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PartName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PartNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_no', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['part_no'],
            },
        ),
        migrations.CreateModel(
            name='PumpMake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PumpModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PumpSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['size'],
            },
        ),
        migrations.CreateModel(
            name='MaterialOfConstruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moc', models.CharField(max_length=100, verbose_name='Material of Construction')),
                ('qty_available', models.PositiveIntegerField(default=0)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('drawing', models.CharField(blank=True, max_length=255, null=True)),
                ('ref_part_list', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('part_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='pump_spares.partname')),
                ('part_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='pump_spares.partnumber')),
                ('pump_make', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='pump_spares.pumpmake')),
                ('pump_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='pump_spares.pumpmodel')),
                ('pump_size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='pump_spares.pumpsize')),
            ],
            options={
                'verbose_name': 'Material of Construction',
                'verbose_name_plural': 'Materials of Construction',
                'ordering': ['pump_make__name', 'pump_model__name', 'pump_size__size', 'part_number__part_no', 'part_name__name', 'moc'],
                'unique_together': {('pump_make', 'pump_model', 'pump_size', 'part_number', 'part_name', 'moc')},
            },
        ),
    ]
