# Generated by Django 5.2.5 on 2025-08-29 11:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pump_spares', '0002_pumpdetailssubmission_pumpdetailsdocument'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EnergyOptimizationSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_type', models.CharField(choices=[('1R + 1S', '1R + 1S - Single Rotor + Single Stage'), ('2R + 1S', '2R + 1S - Double Rotor + Single Stage'), ('MS + MR', 'MS + MR - Multi Stage + Multi Rotor')], max_length=20)),
                ('da_tank_height', models.DecimalField(blank=True, decimal_places=2, help_text='DA Tank Height from Pump Center line (h1) in meters', max_digits=10, null=True)),
                ('boiler_drum_height', models.DecimalField(blank=True, decimal_places=2, help_text='Boiler Drum Height from Pump Center line (h2) in meters', max_digits=10, null=True)),
                ('da_tank_pressure', models.DecimalField(blank=True, decimal_places=2, help_text='DA Tank Pressure (P1) in Kg/cm²', max_digits=10, null=True)),
                ('boiler_drum_pressure', models.DecimalField(blank=True, decimal_places=2, help_text='Boiler Drum Pressure (P2) in Kg/cm²', max_digits=10, null=True)),
                ('feed_water_temp', models.DecimalField(blank=True, decimal_places=2, help_text='Feed Water Temperature (t) in °C', max_digits=10, null=True)),
                ('specific_gravity', models.DecimalField(blank=True, decimal_places=4, help_text='Specific Gravity at t (SG)', max_digits=10, null=True)),
                ('actual_flow_24hrs', models.DecimalField(blank=True, decimal_places=2, help_text='Actual Flow - 24 hrs (Totalizer Reading) (Mact) in TPH', max_digits=10, null=True)),
                ('actual_flow_required', models.DecimalField(blank=True, decimal_places=2, help_text='Actual Flow Required (Qact) in m³/hr', max_digits=10, null=True)),
                ('flow_qnp', models.DecimalField(blank=True, decimal_places=2, help_text='Flow (Qnp) in m³/hr', max_digits=10, null=True)),
                ('head_hnp', models.DecimalField(blank=True, decimal_places=2, help_text='Head (Hnp) in meters', max_digits=10, null=True)),
                ('bkw_bkwnp', models.DecimalField(blank=True, decimal_places=2, help_text='BKW (BKWnp) in KWH', max_digits=10, null=True)),
                ('efficiency', models.DecimalField(blank=True, decimal_places=2, help_text='Efficiency (ηnp) in %', max_digits=5, null=True)),
                ('qhnp_file', models.FileField(blank=True, help_text='QHnp Document', null=True, upload_to='energy_optimization/qhnp/')),
                ('qhact_file', models.FileField(blank=True, help_text='Qnp to Qhact Modification Document', null=True, upload_to='energy_optimization/qhact/')),
                ('qhmod_file', models.FileField(blank=True, help_text='Qhmod Document', null=True, upload_to='energy_optimization/qhmod/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Energy Optimization Submission',
                'verbose_name_plural': 'Energy Optimization Submissions',
                'ordering': ['-created_at'],
            },
        ),
    ]
