# Generated by Django 5.2.5 on 2025-09-03 06:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pump_spares', '0003_energyoptimizationsubmission'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pumpdetailssubmission',
            name='user',
        ),
        migrations.CreateModel(
            name='ReverseEngineeringSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('make', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('flow', models.DecimalField(decimal_places=2, help_text='Flow in m³/hr', max_digits=10)),
                ('head', models.DecimalField(decimal_places=2, help_text='Head in meters', max_digits=10)),
                ('bkw', models.DecimalField(decimal_places=2, help_text='BKW in KWH', max_digits=10)),
                ('efficiency', models.DecimalField(decimal_places=2, help_text='Efficiency in %', max_digits=5)),
                ('pump_curve', models.FileField(blank=True, null=True, upload_to='reverse_engineering/pump_curves/')),
                ('cs_drawing', models.FileField(blank=True, null=True, upload_to='reverse_engineering/cs_drawings/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reverse Engineering Submission',
                'verbose_name_plural': 'Reverse Engineering Submissions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReverseEngineeringDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('document', models.FileField(upload_to='reverse_engineering/additional_docs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reverse_engineering_submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_documents', to='pump_spares.reverseengineeringsubmission')),
            ],
            options={
                'verbose_name': 'Reverse Engineering Additional Document',
                'verbose_name_plural': 'Reverse Engineering Additional Documents',
            },
        ),
        migrations.DeleteModel(
            name='PumpDetailsDocument',
        ),
        migrations.DeleteModel(
            name='PumpDetailsSubmission',
        ),
    ]
