# Generated by Django 5.2.5 on 2025-09-03 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pump_spares', '0004_remove_pumpdetailssubmission_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryDatabase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_name', models.CharField(help_text='Name/description of the part', max_length=200)),
                ('part_no', models.CharField(help_text='Part number', max_length=50)),
                ('drawing', models.CharField(blank=True, help_text='Drawing reference', max_length=255, null=True)),
                ('ref_location', models.CharField(blank=True, help_text='Reference location', max_length=255, null=True)),
                ('moc', models.CharField(help_text='Material of Construction', max_length=100)),
                ('availability', models.PositiveIntegerField(default=0, help_text='Quantity available')),
                ('uom', models.CharField(default='nos', help_text='Unit of measurement', max_length=20)),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Unit price', max_digits=12)),
                ('drawing_vendor', models.CharField(blank=True, help_text='Drawing vendor reference', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Inventory Item',
                'verbose_name_plural': 'Inventory Database',
                'ordering': ['part_no'],
            },
        ),
    ]
