# Generated by Django 5.2.5 on 2025-09-10 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pump_spares', '0005_inventorydatabase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reverseengineeringsubmission',
            name='bkw',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='BKW in KWH', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='reverseengineeringsubmission',
            name='efficiency',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Efficiency in %', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='reverseengineeringsubmission',
            name='flow',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Flow in m³/hr', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='reverseengineeringsubmission',
            name='head',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Head in meters', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='reverseengineeringsubmission',
            name='make',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='reverseengineeringsubmission',
            name='model',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
