# Generated by Django 5.2.5 on 2025-09-16 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pump_spares', '0006_alter_reverseengineeringsubmission_bkw_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='energyoptimizationsubmission',
            name='actual_discharge_pressure',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Actual discharge Pressure (Pd) in Kg/cm²', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='energyoptimizationsubmission',
            name='actual_power_consumption',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Actual Power Consumption (BKW1) in KWH', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='energyoptimizationsubmission',
            name='actual_speed_n2',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Actual running RPM (N2) in RPM', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='energyoptimizationsubmission',
            name='actual_suction_pressure',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Actual Suction Pressure (Ps) in Kg/cm²', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='energyoptimizationsubmission',
            name='analysis_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='energyoptimizationsubmission',
            name='calculated_efficiency_after',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Calculated Efficiency After Optimization (%)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='energyoptimizationsubmission',
            name='calculated_efficiency_before',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Calculated Efficiency Before Optimization (%)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='energyoptimizationsubmission',
            name='co2_reduction_kg',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='CO2 Reduction (kg)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='energyoptimizationsubmission',
            name='cost_saving_per_day',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Cost Saving Per Day', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='energyoptimizationsubmission',
            name='desp_input_file',
            field=models.FileField(blank=True, help_text='DESP-User Input.xlsx', null=True, upload_to='energy_optimization/desp/'),
        ),
        migrations.AddField(
            model_name='energyoptimizationsubmission',
            name='flowchart_file',
            field=models.FileField(blank=True, help_text='FlowChart.pdf', null=True, upload_to='energy_optimization/flowchart/'),
        ),
        migrations.AddField(
            model_name='energyoptimizationsubmission',
            name='payback_period_days',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Payback Period (days)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='energyoptimizationsubmission',
            name='plots_generated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='energyoptimizationsubmission',
            name='power_saving_kwh',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Power Saving (KWH)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='energyoptimizationsubmission',
            name='proposal_generated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='energyoptimizationsubmission',
            name='speed_n1',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='RPM (N1) in RPM', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='energyoptimizationsubmission',
            name='trees_saved',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Number of Trees Saved', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='energyoptimizationsubmission',
            name='actual_flow_24hrs',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total mass Flow Recorded (M24) in TPH', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='energyoptimizationsubmission',
            name='actual_flow_required',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Actual Flow (Qact) in m³/hr', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='energyoptimizationsubmission',
            name='project_type',
            field=models.CharField(choices=[('1R + 1S', '1R + 1S - Single Rotor + Single Stage'), ('2R + 1S', '2R + 1S - Double Rotor + Single Stage'), ('MR + MS', 'MR + MS - Multiple Running & Multiple StandBy')], max_length=20),
        ),
        migrations.AlterField(
            model_name='energyoptimizationsubmission',
            name='qhact_file',
            field=models.FileField(blank=True, help_text='QHact Document', null=True, upload_to='energy_optimization/qhact/'),
        ),
        migrations.AlterField(
            model_name='energyoptimizationsubmission',
            name='qhmod_file',
            field=models.FileField(blank=True, help_text='QHmod Document', null=True, upload_to='energy_optimization/qhmod/'),
        ),
        migrations.AlterField(
            model_name='energyoptimizationsubmission',
            name='qhnp_file',
            field=models.FileField(blank=True, help_text='Upload QHnp of one pump', null=True, upload_to='energy_optimization/qhnp/'),
        ),
    ]
